--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-09-15 23:36:33

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 42092)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id integer NOT NULL,
    category character varying(100) NOT NULL,
    image text NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    difficulty_level character varying(50) NOT NULL,
    "time" text NOT NULL,
    price text NOT NULL,
    suggestion text
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 42091)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.products_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.products_id_seq OWNER TO postgres;

--
-- TOC entry 4850 (class 0 OID 0)
-- Dependencies: 217
-- Name: products_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.products_id_seq OWNED BY public.products.id;


--
-- TOC entry 4695 (class 2604 OID 42095)
-- Name: products id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products ALTER COLUMN id SET DEFAULT nextval('public.products_id_seq'::regclass);


--
-- TOC entry 4844 (class 0 OID 42092)
-- Dependencies: 218
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.products VALUES (1, 'Chaveiro', '1757779509909-chaveiro1.jpeg', 'Girassol, Margarida e Rosa', 'Chaveiro artesanal feito em crochê em formato de flor. Pode ser produzido em diferentes cores, como girassol (amarelo e marrom), margarida (branco e amarelo) e flor decorativa (rosa e branco). A peça é delicada, versátil e pode ser usada tanto como acessório para chaves quanto para bolsas e mochilas, trazendo um toque criativo e personalizado.', 'Fácil a intermediário', '1h a 1h30 por unidade', 'R$ 18,00 e R$ 30,00', 'Uma ótima ideia para valorizar ainda mais a peça é oferecer personalizações, como acrescentar nomes com miçangas ou iniciais em letras, tornando o chaveiro exclusivo para cada cliente. Também pode-se variar nas linhas, utilizando fios com brilho metálico para criar detalhes diferenciados e atrativos. Outra possibilidade é vender kits de flores em diferentes cores, o que aumenta o ticket médio e agrada quem gosta de ter várias opções para combinar. Além disso, investir em uma embalagem simples, como saquinhos de organza ou caixinhas de papel craft, traz um charme especial e faz com que a peça seja vista não apenas como um chaveiro, mas como um presente artesanal cheio de carinho.');
INSERT INTO public.products VALUES (2, 'Chaveiro', '1757879245774-chaveiro2.jpg', 'Água-viva', 'Chaveiro artesanal em crochê em formato de água-viva, com base arredondada e tentáculos feitos em cordões torcidos, criando um efeito realista e delicado. As cores suaves em degradê, como azul com branco ou rosa com branco, dão um ar alegre e lúdico, tornando a peça perfeita para decorar chaves, bolsas ou mochilas, além de ser uma opção encantadora de presente artesanal.', 'Intermediário', '1h30 e 2h por unidade', 'R$ 25,00 a R$ 40,00', 'Essa peça pode ficar ainda mais especial se for vendida em combinações temáticas, como kit de animais marinhos (água-viva, estrela-do-mar, peixinho). Outra ideia é usar fios com efeito degradê ou mesclados, que destacam os tentáculos e dão movimento à peça. Também é possível acrescentar olhos de miçanga ou bordados para dar expressão e deixá-la mais divertida. Embalar em saquinhos transparentes com etiqueta artesanal reforça o valor de produto feito à mão e a torna ideal para lembrancinhas criativas.');
INSERT INTO public.products VALUES (3, 'Roupa', '1757879420421-roupa1.jpg', 'Blusa Cropped Peplum', 'Blusa cropped artesanal feita em crochê, no estilo peplum, com parte superior ajustada em pontos canelados e parte inferior soltinha com babados delicados. As alças finas com amarração nos ombros deixam a peça ainda mais charmosa e versátil. O modelo, em vermelho vibrante, é moderno e elegante, perfeito para compor looks casuais ou românticos.', 'Intermediário a avançado', '10 a 15 horas', 'R$ 120,00 e R$ 200,00', 'Essa blusa pode ser ainda mais valorizada se for oferecida em diferentes cores, especialmente tons neutros como bege, branco e preto, além de versões em degradê para um visual moderno. Também pode ser feita sob medida, garantindo caimento perfeito para cada cliente. Outra ideia é incluir detalhes extras, como botões decorativos ou aplicações delicadas, para agregar valor. Além disso, investir em ensaios fotográficos que mostrem combinações de looks ajudará a destacar a peça como uma opção estilosa e versátil para o guarda-roupa.');
INSERT INTO public.products VALUES (4, 'Porta Livro', '1757879572357-portaLivro1.jpg', 'Capa Porta-livro com Bolso', 'Capa artesanal em crochê feita sob medida para proteger livros ou cadernos, confeccionada em fio cru com detalhe de coração vermelho em square aplicado na parte da frente. Possui bolso funcional que pode ser usado para guardar canetas, marcadores de página e pequenos acessórios. O acabamento lateral em pontos cruzados vermelhos dá um charme extra e reforça o estilo handmade. É uma peça prática, delicada e perfeita para quem ama leitura e organização.', 'Intermediário', '6 a 8 horas', 'R$ 80,00 e R$ 120,00', 'Essa peça pode ser personalizada em diversas cores, com diferentes motivos no square central (flores, estrelas, iniciais ou símbolos), tornando-a exclusiva para cada cliente. Outra ideia é oferecer tamanhos diferentes para livros de bolso, médios e grandes, ou até mesmo para tablets e agendas, ampliando as possibilidades de uso. Embalagens simples, como saquinhos de tecido ou papel craft com laço de barbante, dão um toque especial e fazem com que a peça seja ideal também para presente.');
INSERT INTO public.products VALUES (5, 'Porta Livro', '1757879691850-portaLivro2.jpg', 'Capa Porta-livro em Xadrez', 'Capa artesanal em crochê feita com padrão xadrez em duas cores, resultando em um visual moderno e delicado. O fechamento é feito com um botão branco que garante praticidade e segurança para proteger o livro. Além de funcional, é uma peça decorativa que combina charme retrô com estilo contemporâneo, disponível em combinações como rosa e branco ou verde e branco. Ideal para quem gosta de levar livros na bolsa sem amassar ou sujar, ou simplesmente para deixar a estante mais bonita e personalizada.', 'Intermediário', '6 a 9 horas', 'R$ 90,00 e R$ 130,00', 'Esse modelo pode ser oferecido em várias combinações de cores, desde tons pastéis para um visual mais delicado até cores fortes para um estilo mais ousado. Também é possível personalizar com iniciais bordadas ou etiquetas de couro sintético com nome, tornando a peça única. Outra ideia é criar kits com marcadores de crochê combinando, agregando valor ao conjunto e tornando-o um presente completo para amantes da leitura.');
INSERT INTO public.products VALUES (6, 'Roupa', '1757879835560-roupa2.jpg', 'Cropped Marrom Café', 'Top cropped artesanal em crochê, confeccionado na cor marrom café, transmitindo elegância e versatilidade. O modelo possui bojo triangular, decote profundo em V e amarração no pescoço e nas costas, garantindo ajuste perfeito ao corpo. É uma peça leve, confortável e atemporal, ideal para compor looks de verão, praia ou até combinações casuais com jeans, saias e pantalonas.', 'Intermediário', '8 a 12 horas', 'R$ 85,00 e R$ 120,00', 'Esse modelo pode ser produzido em diferentes cores (tons neutros para looks clássicos e cores vibrantes para um visual mais ousado). Também é possível personalizar adicionando detalhes como franjas, bordados ou acabamentos em fio com brilho para ocasiões especiais. Outra ideia é criar conjuntos com saias ou shorts em crochê combinando, tornando o produto ainda mais atrativo como “look completo”.');
INSERT INTO public.products VALUES (7, 'Acessório de Cabelo', '1757880206234-acessorioCabelo1.jpg', 'Faixa de Cabelo Trama Aberta', 'Faixa de cabelo artesanal feita em crochê, no estilo trama aberta, proporcionando leveza e um visual descontraído. Confeccionada em fio cru, combina facilmente com diversos looks, do casual ao mais sofisticado. É um acessório versátil, que pode ser usado tanto para compor produções de verão, quanto para dar um toque estiloso em ocasiões especiais. Além de prática, mantém os fios no lugar com elegância e originalidade.', 'Básico a intermediário', '2 a 4 horas', 'R$ 35,00 e R$ 55,00', 'Essa faixa pode ser feita em diversas cores para combinar com diferentes estilos e estações. Fios com brilho ou tons vibrantes podem trazer um ar mais moderno, enquanto os neutros permanecem clássicos e versáteis. Outra possibilidade é criar kits com duas ou três faixas em cores diferentes, aumentando o valor percebido e atraindo quem gosta de variar os acessórios.');
INSERT INTO public.products VALUES (32, 'Chaveiro', '1757984844827-chaveiro7.jpg', 'Chaveiro Abelhinha', 'Um chaveiro super fofo e colorido em formato de abelhinha amigurumi, feito à mão com detalhes em preto e amarelo, além de duas asinhas branquinhas que deixam a peça ainda mais charmosa. Macio, delicado e cheio de personalidade, é perfeito para dar vida às suas chaves, bolsas ou mochilas.', 'Intermediário', '2 horas', 'R$ 22,00 e R$ 28,00', 'Esse chaveiro pode ser vendido também em kits temáticos com outros bichinhos (joaninha, borboleta, sapinho etc.), tornando-se um ótimo presente criativo e colecionável.');
INSERT INTO public.products VALUES (8, 'Bolsa', '1757880335503-bolsa1.jpg', 'Bolsa Fundo do Mar', 'Bolsa artesanal em crochê, confeccionada em fio branco com aplicações inspiradas no mar: estrela-do-mar azul, concha bege e uma charmosa água-viva azul com tentáculos em fio solto. Com alça em crochê no mesmo tom, a peça é leve, prática e perfeita para compor looks de verão ou acompanhar passeios descontraídos. O design criativo transmite frescor e um toque divertido, tornando-a ideal tanto para uso casual quanto para quem ama acessórios exclusivos e temáticos.', 'Intermediário a avançado', '12 a 16 horas', 'R$ 130,00 e R$ 180,00', 'Essa bolsa pode ser feita em versões temáticas diferentes, como “florais”, “borboletas” ou “frutas tropicais”, ampliando a coleção. Outra ideia é criar uma linha completa “Fundo do Mar”, incluindo tiaras, chaveiros e até cropped combinando, para quem gosta de conjuntos. Adicionar forro interno em tecido também aumenta a durabilidade e o valor percebido.');
INSERT INTO public.products VALUES (9, 'Chaveiro', '1757880505638-chaveiro3.jpg', 'Chaveiro Amigurumi Totoro', 'Mini chaveiro feito em crochê no estilo amigurumi, inspirado no personagem Totoro, do estúdio Ghibli. Confeccionado em fio cinza com barriguinha branca e olhinhos aplicados, transmite delicadeza e muito charme. Compacto e leve, é perfeito para decorar chaves, bolsas e mochilas, trazendo um toque divertido e único ao dia a dia.', 'Intermediário', '2 a 3 horas cada unidade', 'R$ 25,00 e R$ 40,00 por unidade', 'Esses chaveiros já são naturalmente encantadores, mas você pode valorizar ainda mais criando uma coleção com outros personagens fofos no mesmo estilo, como gatinhos, pandas ou coelhinhos, ampliando as opções para quem gosta de variar. Outra ideia é oferecer kits temáticos, juntando dois ou três chaveiros em uma mesma compra, o que pode atrair clientes que desejam presentear ou colecionar. Além disso, a personalização é um grande diferencial: bordar iniciais no verso ou brincar com diferentes combinações de cores transforma cada peça em algo único, agregando valor e tornando o chaveiro ainda mais especial para quem compra.');
INSERT INTO public.products VALUES (10, 'Roupa', '1757880830165-roupa3.jpg', 'Top cropped em formato de flor', 'Este é um top cropped de crochê feito à mão, com um design central em forma de flor. O miolo da flor é de uma cor (amarelo), as pétalas são de duas cores diferentes (rosa e branco), e há um contorno de crochê branco nas extremidades de cada pétala, o que dá um acabamento delicado e ondulado. A peça é sem alças, com uma única alça de crochê que se amarra no pescoço. Sua parte inferior é mais curta, mostrando o abdômen. A peça é fresca e ideal para dias quentes.

', 'Intermediário', '10 a 15 horas', 'R$ 100,00 a R$ 250,00', 'Essa peça é perfeita para um look de verão ou para festivais de música. Combine-a com uma saia longa de tecido leve ou com shorts jeans de cintura alta para um visual descontraído e elegante. Uma rasteirinha ou um tênis branco simples completam o visual, e você pode adicionar alguns acessórios como colares delicados ou pulseiras finas. Para um dia mais fresco, use a peça por baixo de uma jaqueta jeans ou um cardigan leve.');
INSERT INTO public.products VALUES (11, 'Bolsa', '1757881291690-bolsa2.jpg', 'Bolsa Coração', 'Bolsa artesanal em crochê no formato de coração, feita com fio rosa claro e alça larga também em crochê. O fechamento é simples, utilizando fitas de cetim nas laterais, o que traz um charme delicado e romântico à peça. Compacta e leve, é perfeita para carregar pequenos objetos do dia a dia com estilo e personalidade. Combina tanto com looks casuais quanto com produções mais femininas e delicadas, além de ser uma ótima opção de presente artesanal.
', 'Intermediário', '5 e 8 horas', 'R$ 90,00 e R$ 150,00', 'Essa bolsa pode ser explorada em diferentes cores, como vermelho para um estilo mais apaixonado, branco para um toque mais delicado ou até multicolorida para um visual divertido. Adicionar forro de tecido interno aumenta a durabilidade e a praticidade da peça, permitindo carregar objetos com mais segurança. Pequenos detalhes extras, como flores de crochê aplicadas, pérolas ou botões personalizados, podem agregar ainda mais valor. Também é possível criar versões infantis em tamanhos menores ou versões maiores como bolsas de ombro, ampliando as opções para diferentes públicos.');
INSERT INTO public.products VALUES (12, 'Marca Página', '1757881496995-marcaPagina1.jpg', 'Marca-página Margarida e Girassol', 'Marca-página artesanal feito em crochê, composto por pequenas flores unidas em sequência, resultando em um acessório delicado e funcional. Cada extremidade é finalizada com um tassel que garante charme extra e ajuda a manter o marcador firme entre as páginas. As cores podem variar entre tons vibrantes, como amarelo e laranja, ou tons neutros e suaves, como branco e bege, permitindo combinações que vão do alegre ao romântico. É um item prático para leitores que desejam marcar suas páginas com estilo, além de ser uma opção encantadora de presente artesanal.', 'Básico e intermediário', '1h30 a 3h por unidade', 'R$ 25,00 e R$ 45,00', 'Esse modelo pode ser oferecido em diversas paletas de cores, como tons pastéis para um estilo delicado, cores fortes para um visual vibrante ou até combinações sazonais, como vermelho e verde no Natal ou laranja e preto para o Halloween. Também é possível criar kits com dois ou três marca-páginas diferentes, tornando-os presentes criativos e acessíveis para amantes da leitura. Outra ideia é personalizar com pequenas miçangas ou pérolas no centro das flores, dando um toque sofisticado e exclusivo.');
INSERT INTO public.products VALUES (13, 'Porta Copos', '1757881824414-portaCopo1.jpg', 'Porta-copos Flor Sorridente', 'Porta-copos artesanal feito em crochê no formato de flor, com centro amarelo e pétalas brancas. O detalhe do rostinho sorridente bordado no centro deixa a peça divertida, alegre e cheia de personalidade, ideal para trazer charme à mesa e proteger superfícies de respingos e calor das bebidas. Além de funcional, é um item decorativo que combina com ambientes descontraídos e acolhedores, perfeito para cafés da manhã, encontros entre amigos ou para dar de presente em kits criativos.', 'Básico e intermediário', '1h a 2h por unidade', 'R$ 15,00 e R$ 25,00', 'Essa peça pode ser oferecida em diferentes combinações de cores, como flores coloridas (rosa, azul, lilás, laranja) ou até em versão minimalista (branco e preto) para se adaptar a vários estilos de decoração. Também é possível montar kits temáticos com embalagens personalizadas, que funcionam muito bem como lembrancinhas de aniversário, chá de cozinha, Dia das Mães ou presentes criativos para amigos. Outra ideia é variar os bordados, criando carinhas diferentes (piscando, com óculos, corações nos olhos) para deixar os conjuntos ainda mais divertidos e exclusivos.');
INSERT INTO public.products VALUES (14, 'Chaveiro', '1757882661001-chaveiro4.jpg', 'Chaveiro Flor', 'Chaveiro artesanal feito em crochê no formato de flor de cinco pétalas, em fio branco com detalhe central em rosa claro. É um acessório delicado, leve e funcional, perfeito para personalizar chaves, bolsas e mochilas com um toque artesanal e romântico. Além de ser útil, também é um mimo criativo que pode ser oferecido como lembrancinha em aniversários, chás de bebê, casamentos ou simplesmente como presente carinhoso para alguém especial.', 'Básico', '30 a 50 minutos por unidade', 'R$ 8,00 e R$ 15,00', 'Esse chaveiro pode ser feito em diversas combinações de cores, como flores coloridas para um estilo alegre ou tons pastéis para um visual delicado. Também é possível personalizar com pérolas ou miçangas no centro, ou ainda adicionar etiquetas de couro sintético com nomes para torná-los exclusivos. Oferecer kits temáticos ou embalagens personalizadas aumenta o valor percebido e torna a peça ainda mais atrativa para presentes e lembrancinhas.');
INSERT INTO public.products VALUES (15, 'Roupa', '1757882836368-roupa4.jpg', 'Top Faixa com Nó Torcido', 'Top artesanal em crochê confeccionado em listras horizontais nas cores azul bebê e branco. O destaque da peça é o nó torcido na parte frontal, que cria um recorte moderno e valoriza o busto, deixando o visual estiloso e descontraído. Feito à mão com pontos simples e fio confortável, é uma peça leve, fresca e perfeita para os dias de verão. Pode ser usado tanto como saída de praia quanto em looks casuais, combinando com shorts, saias ou calças de cintura alta.', 'Intermediário', '6 a 10 horas', 'R$ 120,00 e R$ 180,00', 'Esse modelo pode ser explorado em diferentes combinações de cores, desde tons pastéis delicados até cores vibrantes e contrastantes. Também é possível adaptar a peça com alças removíveis ou amarrações nas costas, oferecendo mais sustentação e variedade de estilos. Para valorizar ainda mais o trabalho, vale oferecer versões personalizadas sob medida, tornando o top exclusivo para cada cliente.');
INSERT INTO public.products VALUES (16, 'Roupa', '1757883001690-roupa5.jpg', 'Top Moranguinho', 'Top artesanal em crochê inspirado no estilo retrô e romântico, confeccionado em branco com detalhes em vermelho e verde. A peça apresenta alças largas, acabamento delicado em ponto fantasia e aplicação de moranguinhos em crochê, que trazem um charme divertido e exclusivo. O fechamento frontal é feito com amarração em cordão verde, proporcionando ajuste perfeito ao corpo e um toque de originalidade. É uma peça leve, estilosa e ideal para looks de verão, podendo ser combinada com shorts, saias ou jeans para um visual despojado e cheio de personalidade.', 'Intermediário a avançado', '8 a 12 horas', 'R$ 140,00 e R$ 200,00', 'Esse top pode ser adaptado em outras frutas, como cerejinhas, laranjas ou limões, criando uma coleção temática divertida e colecionável. Outra ideia é oferecer personalização de cores, como tons pastéis para um visual delicado ou combinações vibrantes para um estilo ousado. Também é possível produzir versões mais compridas como cropped estilo regata ou até vestidos curtos seguindo o mesmo conceito, ampliando as opções para diferentes clientes.');
INSERT INTO public.products VALUES (17, 'Acessório de Cabelo', '1757883134012-acessorioCabelo2.jpg', 'Tiara Faixa', 'Tiara artesanal em crochê feita com ponto rendado delicado, em fio cru. É uma peça versátil e confortável, que pode ser usada tanto para dar um toque romântico ao look quanto para manter os cabelos no lugar de forma charmosa. Seu design leve e trabalhado à mão valoriza penteados soltos ou presos, combinando com diferentes estilos — do casual ao boho. É perfeita para complementar produções de verão, passeios ao ar livre ou até mesmo ocasiões especiais em que se busca um acessório único e artesanal.', 'Intermediário', '2 a 4 horas', 'R$ 25,00 e R$ 45,00', 'Essa tiara pode ser feita em várias cores para combinar com diferentes estilos e estações. Tons neutros como bege, branco e cinza dão um ar minimalista, enquanto cores vivas como vermelho, azul ou amarelo deixam a peça mais divertida. Também é possível acrescentar detalhes como pérolas costuradas, flores pequenas em crochê ou até fios com brilho para versões mais sofisticadas. Uma boa estratégia de venda é oferecer kits com 2 ou 3 unidades em cores variadas, ideais para quem gosta de mudar o visual sem abrir mão do artesanato.');
INSERT INTO public.products VALUES (18, 'Bolsa', '1757883410920-bolsa3.jpg', 'Bolsa Quadradinhos com Corações', 'Bolsa artesanal feita em crochê com a técnica de granny squares, composta por quadrados vermelhos e brancos decorados com corações em relevo. É uma peça romântica, moderna e super charmosa, ideal para quem ama acessórios únicos e feitos à mão. Além de estilosa, é resistente e prática para o dia a dia, comportando desde itens pessoais até pequenos objetos de uso cotidiano.', 'Intermediário', '8 a 12 horas', 'R$ 120,00 e R$ 180,00', 'É possível explorar diferentes paletas de cores para adaptar a bolsa a diferentes estilos, como combinações suaves em tons pastéis ou contrastes mais modernos em cores vibrantes. Outra ideia é adicionar forro em tecido, o que garante maior resistência e funcionalidade, além de permitir guardar objetos menores com segurança. Oferecer versões personalizadas sob encomenda pode valorizar ainda mais o trabalho, tornando cada bolsa exclusiva e especial para a cliente.');
INSERT INTO public.products VALUES (19, 'Bolsa', '1757883708587-bolsa4.jpg', 'Bolsa Summer', 'Bolsa artesanal em crochê confeccionada com fio de malha branco, que garante estrutura firme e visual moderno. O modelo apresenta um formato retangular compacto, ideal para levar o essencial com estilo. A alça larga, também em crochê, é fixada com argolas metálicas que trazem resistência e um toque sofisticado. O detalhe especial fica por conta do enfeite em acrílico transparente em forma de flor, que adiciona delicadeza e charme ao design minimalista. É uma peça versátil, perfeita para passeios na praia, encontros casuais ou até para compor looks urbanos descontraídos.', 'Básico e intermediário', '6 a 8 horas', 'R$ 130,00 e R$ 180,00', 'Esse modelo pode ganhar versões ainda mais exclusivas com o uso de cores vibrantes ou combinações bicolores. Outra ideia é acrescentar forro interno em tecido, oferecendo mais segurança e durabilidade. O enfeite pode ser personalizado — como flores de crochê, pompons ou aplicações em metal — para atender diferentes estilos e preferências de clientes.');
INSERT INTO public.products VALUES (20, 'Marca Página', '1757883903953-marcaPagina2.jpeg', 'Marca-página Xícara de Café', 'Marca-página artesanal em crochê no formato de uma delicada xícara de café branca com interior marrom, que representa o café servido. O fio longo e fino se estende até um pingente em forma de tassel marrom, criando um detalhe charmoso e funcional. A peça é leve, criativa e ideal para acompanhar momentos de leitura, trazendo aconchego e um toque artesanal único ao livro. Além de útil, é um presente encantador para amantes de café e leitura.', 'Básico e intermediário', '2 a 3 horas', 'R$ 25,00 e R$ 40,00', 'Esse modelo pode ser personalizado em diferentes cores para representar outras bebidas, como chá ou chocolate quente, além de variar o tom do tassel para criar combinações divertidas. Outra ideia é montar kits com diferentes versões do marca-página, tornando-o um produto perfeito para presentes criativos e lembrancinhas temáticas.');
INSERT INTO public.products VALUES (21, 'Marca Página', '1757884869591-marcaPagina3.jpg', 'Marca-página Laço', 'Marca-página delicado em crochê, composto por um laço rosa na parte superior e uma pequena flor na extremidade do fio branco, finalizada com detalhe em pérola no centro. O design transmite romantismo e sutileza, tornando a leitura ainda mais encantadora. É uma peça artesanal charmosa, perfeita para marcar páginas de forma criativa e dar um toque especial aos livros.', 'Intermediário', '3 a 4 horas', 'R$ 30,00 e R$ 50,00', 'Esse modelo pode ser adaptado em diferentes cores e combinações, como laços em tons pastéis ou vibrantes, além de variações de flores com ou sem pérolas. Também é possível criar coleções temáticas, oferecendo kits com diferentes modelos de marca-página, tornando o produto ainda mais atrativo para presentes delicados e personalizados.');
INSERT INTO public.products VALUES (31, 'Chaveiro', '1757984730906-chaveiro6.jpg', 'Chaveiro Lua e Estrela', 'Um par encantador de chaveiros feitos à mão em crochê: uma estrela azul sorridente e uma lua amarela delicada, ambos com detalhes bordados que dão um toque fofo e acolhedor. Leves e macios, são perfeitos para personalizar suas chaves, mochilas ou bolsas, trazendo charme e alegria para o dia a dia.', 'Básico e intermediário', '1 a 2 horas', 'R$ 18,00 e R$ 25,00 por unidade', 'Esses chaveiros podem ser vendidos também como lembrancinhas de aniversário, batizado ou eventos temáticos, além de combinações personalizadas (como sol, nuvem, coração, etc.), formando kits criativos.');
INSERT INTO public.products VALUES (22, 'Chaveiro', '1757885037829-chaveiro5.jpg', 'Chaveiro Laço', 'Chaveiro artesanal em formato de laço, confeccionado em crochê com pontos firmes e bem estruturados. O design transmite delicadeza e charme, ideal para quem gosta de acessórios românticos e elegantes. Cada peça recebe detalhes especiais com miçangas e pedrarias, que acrescentam sofisticação e tornam o chaveiro ainda mais único. Disponível em cores como rosa e branco, é um acessório versátil que pode ser usado para enfeitar chaves, bolsas ou mochilas, agregando um toque de personalidade ao dia a dia.', 'Básico e intermediário', '2 a 3 horas', 'R$ 18,00 e R$ 35,00', 'Esse modelo pode ser confeccionado em diferentes cores e tamanhos, possibilitando desde versões delicadas e minimalistas até laços maiores e mais chamativos. Também é possível criar coleções temáticas, como chaveiros em tons pastéis, vibrantes ou metalizados, oferecendo opções personalizadas que agradam a diferentes perfis de clientes.');
INSERT INTO public.products VALUES (23, 'Roupa', '1757885157996-roupa6.jpg', 'Top Cropped Toamara-que-Caia', 'Um top cropped tomara-que-caia confeccionado em crochê, que combina charme e frescor para dias ensolarados. A parte superior traz listras delicadas em rosa e branco, com detalhe central franzido que valoriza o busto de forma elegante. Já a parte inferior possui acabamento em babado evasê, criando movimento e um caimento leve, que acrescenta feminilidade e estilo ao visual. Confortável e moderno, é perfeito para compor looks casuais com shorts, saias ou calças jeans, sendo também uma ótima opção para ocasiões na praia, passeios ou encontros informais.', 'Intermediário', '6 a 10 horas', 'R$ 85,00 e R$ 150,00', 'Esse modelo pode ser adaptado em diferentes combinações de cores, desde tons vibrantes até os mais neutros. Também pode ganhar variações com alcinhas finas para quem busca mais segurança ou detalhes extras, como aplicação de pérolas ou bordados, tornando-o ainda mais exclusivo.');
INSERT INTO public.products VALUES (24, 'Porta Livro', '1757885338724-portaLivro3.jpg', 'Porta-Livro Rosa Tulipas', 'Porta-livro artesanal em crochê feito à mão na cor rosa bebê, com delicados bordados florais que remetem a pequenos botões de rosas em tom pink com folhas verdes. A peça conta com fechamento em aba com botão, garantindo praticidade e proteção ao livro. Além de funcional, traz um charme romântico e atemporal, ideal para quem deseja transportar ou guardar seus livros de forma elegante e personalizada. Seu design acolhedor transforma a leitura em um momento ainda mais especial, unindo utilidade e beleza em cada detalhe.', 'Intermediário', '8 a 12 horas', 'R$ 90,00 e R$ 150,00', 'Esse modelo pode ser facilmente adaptado em outras cores, como lilás, azul claro ou bege, mantendo os bordados florais em contraste. Também é possível personalizar com iniciais ou pequenos apliques, tornando o porta-livro uma peça exclusiva e perfeita para presentes.');
INSERT INTO public.products VALUES (25, 'Porta Livro', '1757885472244-portaLivro4.jpg', 'Porta-Livro Morango', 'Porta-livro artesanal em crochê inspirado na doçura e no charme do morango. A peça é confeccionada em vermelho vivo, com pequenos pontos brancos que remetem às sementes da fruta. O acabamento em verde, junto ao botão de fechamento, representa as folhinhas do morango, trazendo delicadeza e um visual divertido. Além de proteger o livro contra riscos e desgastes, o acessório transforma a leitura em um momento ainda mais especial, unindo funcionalidade e estilo.', 'Intermediário', '6 a 9 horas', 'R$ 70,00 e R$ 120,00', 'Esse modelo pode ganhar versões em diferentes frutas, como melancia, abacaxi ou laranja, formando uma coleção criativa e alegre. Também é possível personalizar com bordados de flores ou iniciais, tornando a peça exclusiva para cada cliente.');
INSERT INTO public.products VALUES (26, 'Acessório de Cabelo', '1757885658868-acessorioCabelo3.jpg', 'Tiara Corações', 'Tiara artesanal em crochê confeccionada com base em azul marinho e detalhes em branco, formando delicados corações ao longo de toda a peça. O contraste das cores dá um charme especial, enquanto o design leve e macio garante conforto ao usar. Ideal para compor penteados românticos ou dar um toque divertido ao visual do dia a dia, sendo uma opção fofa e versátil para todas as idades.', 'Intermediário', '3 a 5 horas', 'R$ 35,00 e R$ 55,00', 'Esse modelo pode ser feito em diversas combinações de cores, como vermelho e branco para um estilo apaixonado ou tons pastel para um visual delicado. Outra ideia é adaptar o acessório em versão infantil, criando conjuntos mãe e filha.');
INSERT INTO public.products VALUES (27, 'Acessório de Cabelo', '1757885838558-acessorioCabelo4.jpg', 'Tiara Floral', 'Tiara delicada confeccionada em crochê, com base em verde que imita ramos e pequenas flores cor-de-rosa aplicadas ao longo de toda a peça. O acessório é leve, romântico e cheio de detalhes, perfeito para criar um visual natural e encantador. Pode ser usado em ocasiões especiais, como casamentos ao ar livre e festas temáticas, ou no dia a dia para dar um toque boho e feminino ao penteado.', 'Intermediário', '4 a 6 horas', 'R$ 45,00 e R$ 70,00', 'Esse modelo pode ser personalizado com flores em diferentes cores, como lilás, azul ou amarelo, criando versões exclusivas para cada cliente. Outra ideia é adaptar o acessório como guirlanda decorativa ou até mesmo faixa para bebês, tornando-o ainda mais versátil.');
INSERT INTO public.products VALUES (28, 'Acessório de Cabelo', '1757885945614-acessorioCabelo5.jpg', 'Lenço com Squares Florais', 'Lenço artesanal feito em crochê com união de quadradinhos (granny squares) em tom cru, cada um decorado com uma delicada flor central azul com miolo rosa. O acabamento em ondas dá um caimento leve e romântico, transformando o acessório em um charme vintage para compor penteados soltos ou presos. Versátil e estiloso, combina perfeitamente com looks boho, românticos ou casuais.', 'Intermediário', '6 a 8 horas', 'R$ 70,00 e R$ 110,00', 'Você pode criar versões em diferentes combinações de cores (flores amarelas, lilases ou vermelhas, por exemplo) ou até usar fio mesclado para um efeito mais moderno. Outra ideia é aumentar a peça e transformá-la em uma bandana maior ou até em um mini-xale multifuncional.');
INSERT INTO public.products VALUES (29, 'Bolsa', '1757886152592-bolsa5.jpg', 'Bolsa com Fio de Malha Pink', 'Bolsa artesanal confeccionada em crochê com fio de malha na cor pink vibrante. O modelo possui alças curtas integradas à própria estrutura, garantindo resistência e conforto ao carregar. De tamanho médio, é prática e moderna, perfeita para o dia a dia ou para dar um toque fashion em produções casuais. Sua textura encorpada valoriza o trabalho manual e a deixa ainda mais única.', 'Básico e intermediário', '4 a 6 horas', 'R$ 90,00 e R$ 150,00', 'Esse modelo pode ganhar versões em outras cores tendência, como verde oliva, bege, preto ou até combinações bicolores. Também é possível adicionar um forro de tecido com bolsinho interno para maior praticidade e sofisticação.');
INSERT INTO public.products VALUES (30, 'Bolsa', '1757886273782-bolsa6.jpg', 'Bolsa Granny Square Colorida', 'Bolsa artesanal feita em crochê no clássico estilo granny square, unindo cores vibrantes como laranja, rosa, vermelho e lilás, em contraste com o branco cru. O modelo é espaçoso e leve, ideal para usar em passeios, praia ou no dia a dia, trazendo um ar descontraído e retrô. As alças médias permitem carregar no ombro com conforto, enquanto o design colorido dá destaque a qualquer look.', 'Intermediário', '6 a 8 horas', 'R$ 120,00 e R$ 200,00', 'Esse modelo fica incrível em combinações personalizadas — tons pastel para um ar delicado, cores sóbrias para algo sofisticado ou neon para um visual moderno e despojado. Um forro de algodão pode deixar a peça ainda mais resistente e prática.');
INSERT INTO public.products VALUES (33, 'Roupa', '1757985073960-roupa7.jpg', 'Blusa Cropped Amarelinha', 'Uma blusa super delicada e romântica, feita em crochê na cor amarela vibrante que traz alegria e leveza ao look. O modelo possui alcinhas largas com detalhe em babadinho, amarração frontal e caimento soltinho abaixo do busto, garantindo charme e conforto. É uma peça versátil que combina tanto com saias quanto com calças, perfeita para dias ensolarados e encontros especiais.', 'Intermediário', '10 a 14 horas', 'R$ 120,00 e R$ 160,00', 'Essa peça pode ser feita sob medida em outras cores, como branco, lilás, azul ou rosa, para atender diferentes estilos. Também fica linda em conjunto com saias de crochê no mesmo fio.');
INSERT INTO public.products VALUES (34, 'Porta Livro', '1757985208949-portaLivro5.jpg', 'Porta-Livro Moranguinho', 'Um acessório cheio de charme e funcionalidade! Esse porta-livro foi feito em crochê, inspirado nas cores e no formato de um morango. A base vermelha com detalhes em branco lembra as sementinhas da fruta, enquanto a aba verde traz o toque das folhinhas, finalizada com flores delicadas em crochê. Ideal para proteger livros, agendas ou cadernos, além de ser uma peça artesanal única que deixa sua leitura ainda mais especial. 💕', 'Intermediário', '8 a 12 horas', 'R$ 90,00 e R$ 130,00', 'Pode ser feito sob encomenda em outras combinações de cores e tamanhos, perfeito para presentear apaixonados por leitura.');
INSERT INTO public.products VALUES (35, 'Porta Livro', '1757985316489-portaLivro6.jpg', 'Porta-Livros Candy', 'Um charme em forma de proteção para seus livros, agendas ou diários! Esses porta-livros em crochê foram feitos em tons delicados de rosa e branco, com acabamento refinado e detalhe de moldura central que traz um toque personalizado. O laço de fita deixa a peça ainda mais romântica e especial.', 'Intermediário', '10 a 14 horas', 'R$ 95,00 e R$ 140,00', 'Pode ser feito sob encomenda com nomes bordados ou cores personalizadas, ideal para presentear em aniversários, maternidade ou datas especiais.');
INSERT INTO public.products VALUES (36, 'Porta Livro', '1757985406089-portaLivro7.jpg', 'Porta-Livros Envelope do Amor', 'Elegância e delicadeza em forma de crochê! Esse porta-livros em estilo envelope traz um design minimalista e sofisticado, feito em tom cru e finalizado com um botão em formato de coração rosa que dá o charme especial.', 'Intermediário', '8 a 12 horas', 'R$ 85,00 e R$ 120,00', 'Perfeito como presente de Dia dos Namorados, aniversários ou para quem ama leitura com estilo. Pode ser feito em diferentes cores para combinar com a personalidade do cliente.');
INSERT INTO public.products VALUES (37, 'Acessório de Cabelo', '1757985499822-acessorioCabelo6.jpg', 'Tiara Colorida Arco-Íris', 'Tiara de crochê feita à mão, com listras em tons alegres de laranja, azul, creme e vermelho. Um acessório leve, confortável e super estiloso, perfeito para dar aquele toque divertido e único em qualquer look.', 'Básico e intermediário', '3 a 5 horas', 'R$ 35,00 e R$ 55,00', 'Pode ser feita em combinações de cores personalizadas — desde tons pastel delicados até contrastes vibrantes para quem ama ousar.');
INSERT INTO public.products VALUES (38, 'Acessório de Cabelo', '1757985589413-acessorioCabelo7.jpg', 'Tiara Ondas do Mar', 'Tiara de crochê em ponto ondulado (zigue-zague), feita em tons delicados de azul e branco. O design lembra ondas do mar, trazendo leveza e frescor para qualquer visual. Um acessório romântico, moderno e cheio de charme, perfeito para combinar com looks casuais ou até produções mais sofisticadas.', 'Intermediário', '4 a 6 horas', 'R$ 40,00 e R$ 65,00', 'Pode ser feita em outras combinações de cores — como tons pastel para um ar delicado ou contrastes fortes para um look fashionista.');
INSERT INTO public.products VALUES (39, 'Chaveiro', '1757985745614-chaveiro8.jpg', 'Chaveiro Sorvetinho', 'Chaveiro super fofo em formato de sorvete casquinha, feito em crochê com detalhe de bola em rosa (morango) e branco (baunilha). Uma peça charmosa, divertida e delicada para enfeitar bolsas, mochilas ou chaves. Ideal para presentear ou colecionar!', 'Básico e intermediário', '1 a 2 horas por unidade', 'R$ 15,00 e R$ 25,00', 'Monte uma coleção de sorvetinhos com cores que remetam a sabores diferentes, como chocolate (marrom), pistache (verde), banana (amarelo), uva (lilás) e morango (rosa). A versão com corrente dourada ou prateada também agrega valor e sofisticação.');
INSERT INTO public.products VALUES (40, 'Bolsa', '1757985864485-bolsa7.jpg', 'Bolsa Vazada com Fio de Malha Pink + Chaveiro Flor', 'Bolsa artesanal confeccionada em crochê com fio de malha na cor pink intensa. O modelo tem alças médias integradas, proporcionando praticidade e conforto no uso diário. Sua trama vazada dá leveza e modernidade à peça, tornando-a ideal para passeios e looks casuais descontraídos. O detalhe do chaveiro flor de crochê amarelo traz um charme extra, deixando a bolsa ainda mais divertida e única.', 'Intermediário', '5 a 7 horas', 'R$ 120,00 e R$ 180,00', 'Esse modelo pode ser produzido em cores neutras (preto, bege, marrom) para versões mais versáteis, ou em tons vibrantes (verde, laranja, azul) para destacar o visual. O chaveiro flor pode ser trocado por outros acessórios, como borboletas, corações ou pingentes personalizados.');
INSERT INTO public.products VALUES (41, 'Acessório de Cabelo', '1757986021892-acessorioCabelo8.jpg', 'Tiara Cru com Bordado Azul', 'Tiara artesanal confeccionada em crochê com fio cru, decorada com bordados em azul que lembram flores estilizadas. A peça é confortável, delicada e ao mesmo tempo marcante, ideal para dar um charme especial a penteados simples ou deixar o cabelo solto com estilo. Versátil, pode ser usada em ocasiões casuais ou até mesmo para compor looks românticos e criativos.', 'Intermediário', '2 e 4 horas', 'R$ 35,00 e R$ 60,00', 'Esse modelo pode ganhar versões em diferentes combinações de cores (ex.: fundo preto com bordado branco, fundo bege com bordado vermelho) para atender estilos variados. Também pode ser adaptado para faixas infantis, acrescentando aplicações extras como flores ou pérolas.');
INSERT INTO public.products VALUES (42, 'Acessório de Cabelo', '1757986133287-acessorioCabelo9.jpg', 'Tiara Rosa Básica', 'Tiara artesanal feita em crochê com fio rosa em ponto simples, resultando em uma peça macia, confortável e charmosa. O modelo é versátil, combina facilmente com diversos estilos e adiciona um toque delicado ao visual. Ideal para o dia a dia, para compor looks casuais ou dar um ar romântico em produções mais femininas.', 'Básico', '1 e 3 horas', 'R$ 25,00 e R$ 45,00', 'Essa tiara pode ser feita em diversas cores — como lilás, azul bebê, bege ou até tons vibrantes como vermelho e amarelo — para agradar diferentes estilos. Também pode receber aplicações extras, como bordados, flores ou pérolas, agregando ainda mais valor à peça.');
INSERT INTO public.products VALUES (43, 'Marca Página', '1757986229999-marcaPagina4.jpg', 'Marca-página Rosa com Borda Branca', 'Marca-páginas artesanal confeccionado em crochê com fio rosa, acabamento em borda branca ondulada e detalhe delicado de laço no topo. Além de funcional, é um acessório encantador que traz charme à leitura, ideal para presentear ou usar em livros e cadernos.', 'Básico', '1 e 2 horas', 'R$ 15,00 e R$ 30,00', 'Esse modelo pode ser produzido em diversas combinações de cores (como azul com branco, lilás com bege ou até multicolorido). Também é possível personalizar com apliques em forma de flor, coração ou iniciais bordadas para torná-lo ainda mais especial.');
INSERT INTO public.products VALUES (44, 'Marca Página', '1757986334459-marcaPagina5.jpg', 'Marca-página com Coração', 'Marca-páginas artesanal feito em crochê, com corpo alongado e aplicação de coração na ponta. Disponível em cores suaves como branco e rosa, é um acessório romântico e funcional que traz charme à leitura. Ideal para presentear, lembrancinhas ou uso pessoal.', 'Básico', '30 minutos e 1 horas', 'R$ 12,00 e R$ 25,00', 'Pode ser personalizado em diferentes cores (azul, lilás, vermelho, verde) e até com fios com brilho ou degradê. Outra ideia é substituir o coração por outros apliques, como flor, estrela ou borboleta, tornando a peça ainda mais versátil e colecionável.');
INSERT INTO public.products VALUES (45, 'Marca Página', '1757986426191-marcaPagina6.jpg', 'Marca-página Borboleta', 'Marca-páginas artesanal em crochê, feito com fio cru e detalhe em formato de borboleta nas pontas, em cores suaves como lilás e azul. Além de funcional, é um acessório delicado que deixa a leitura mais charmosa e personalizada.', 'Básico e intermediário', '30 minutos e 1 hora por unidade', 'R$ 15,00 e R$ 28,00', 'Pode ser feito em diferentes combinações de cores (pastéis, vibrantes ou com fio mesclado). Também é uma ótima opção de lembrancinha para eventos como dia do professor, chá de bebê ou kits para amantes da leitura.');
INSERT INTO public.products VALUES (46, 'Porta Copo', '1757986545338-portaCopo2.jpg', 'Porta-copos Gato', 'Porta-copos artesanal em crochê, confeccionado em formato de gatinho com orelhinhas e cauda delicada. Feito em fio de algodão, é resistente, lavável e perfeito para proteger superfícies de manchas e calor. Além de útil, traz um charme divertido e aconchegante para a mesa ou cantinho do café.', 'Básico e intermediário', '40 minutos e 1 hora por unidade', 'R$ 12,00 e R$ 22,00', 'Pode ser feito em diversas cores (preto, branco, cinza, marrom, mesclado) para representar diferentes gatinhos. Também pode ser vendido em kits temáticos, ótimo para presente de Dia das Mães, amantes de gatos ou lembrancinhas criativas.');
INSERT INTO public.products VALUES (47, 'Porta Copo', '1757986629553-portaCopo3.jpg', 'Porta-copos Ovelhinha', 'Porta-copos artesanal em crochê, em formato de ovelha simpática. O corpo é feito em espiral com pontos que lembram lã fofinha, enquanto cabeça, patas e orelhas em contraste dão o charme especial. Ideal para decorar e proteger superfícies de manchas de copos e canecas.', 'Intermediário', '1 e 2 hora', 'R$ 18,00 e R$ 28,00', 'Esse modelo pode ser feito em outras cores divertidas (ovelha marrom, cinza, até colorida) para deixar a peça ainda mais personalizada. Também pode ser vendido em kits com outros bichinhos (gato, coelho, ursinho), formando uma coleção de porta-copos animais.');
INSERT INTO public.products VALUES (48, 'Porta Copo', '1757986744790-portaCopo4.jpg', 'Porta-copos Moranguinhos', 'Porta-copos artesanal confeccionado em crochê na base branca, com aplicação de pequenos morangos ao redor, formando um detalhe encantador e colorido. A borda com pontos vazados dá leveza e delicadeza à peça, tornando-a perfeita para compor mesas divertidas e charmosas.', 'Intermediário', '1 e 2 hora', 'R$ 20,00 e R$ 30,00', 'Esse modelo pode ser feito em versões temáticas com outras frutas, como laranja, limão, uva ou cereja, criando uma coleção de porta-copos “Frutinhas”. Outra opção é usar fio com brilho ou mesclado para dar um charme especial às bordas.');
INSERT INTO public.products VALUES (49, 'Chaveiro', '1757986916942-chaveiro9.jpg', 'Chaveiro Mini Polvinho Amigurumi', 'Chaveiro artesanal em crochê, feito com a técnica de amigurumi. Cada polvinho possui olhinhos aplicados e um sorriso bordado, transmitindo fofura e alegria. Disponível em diversas cores vibrantes e delicadas, é perfeito para decorar chaves, bolsas ou mochilas.', 'Intermediário', '40 minutos e 1 hora por unidade', 'R$ 18,00 e R$ 25,00', 'Esse modelo pode ser feito em coleções temáticas, como arco-íris, tons pastéis ou cores neon. Também é possível adicionar acessórios, como mini lacinho, chapéuzinho ou coraçãozinho em crochê, para personalizar cada polvinho.');
INSERT INTO public.products VALUES (50, 'Roupa', '1757987088705-roupa8.jpg', 'Blusa Cropped com Manga Bufante', 'Blusa cropped artesanal feita em crochê, com busto estruturado em formato de bojo e mangas bufantes que trazem um ar romântico e elegante. O corpo ajustado valoriza a silhueta, enquanto a barra com acabamento delicado garante um toque de charme extra. Ideal para compor looks casuais ou sofisticados, dependendo da combinação.', 'Avançado', '12 e 15 horas', 'R$ 160,00 e R$ 220,00', 'Pode ser confeccionada em cores variadas (tons pastéis, vibrantes ou neutros) e também em fio com brilho para ocasiões especiais. Outra opção é adaptar as mangas (curtas, 3/4 ou longas) para criar diferentes estilos.');
INSERT INTO public.products VALUES (51, 'Porta Copo', '1757987229033-portaCopo5.jpg', 'Porta-copo Vitória-Régia', 'Porta-copos artesanal inspirado na folha de vitória-régia, confeccionado em fio verde com detalhe de pequena flor rosa aplicada na borda. O formato arredondado com recorte lateral remete à clássica planta aquática, trazendo um charme único e natural para a peça. Ideal para compor mesas criativas e dar um toque de natureza à decoração.', 'Intermediário', '1 e 2 horas', 'R$ 18,00 e R$ 28,00', 'Esse modelo pode ser produzido em diferentes combinações de cores para as flores (branco, lilás, vermelho) e até em tamanhos maiores para servir como centro de mesa. Também pode ser vendido em kits temáticos com outras versões de flores e folhas.');
INSERT INTO public.products VALUES (52, 'Porta Copo', '1757987315846-portaCopo6.jpg', 'Porta-copo Patinha', 'Porta-copos artesanal confeccionado em crochê no formato de patinha, com base rosa e contorno branco. O design divertido e delicado transmite aconchego e é perfeito para amantes de animais. Além de funcional, é uma peça que traz personalidade e carinho para a decoração da mesa.', 'Intermediário', '1 e 2 horas', 'R$ 20,00 e R$ 30,00', 'Esse modelo pode ser feito em diferentes combinações de cores (como marrom, cinza, bege, azul ou lilás), representando patinhas de vários animais. Outra ideia é criar um kit temático “Mundo Pet” com pegadas de cachorro, gato e até ossinhos em crochê.');
INSERT INTO public.products VALUES (53, 'Porta Copo', '1757987422421-portaCopo7.jpg', 'Porta-copo Rosinhas', 'Porta-copos artesanal em crochê, com base circular em tom rosado e acabamento encantador de pequenas rosas em volta, nas cores rosa claro e rosa escuro, com folhinhas verdes. O detalhe das flores dá um toque delicado e romântico, perfeito para decorar mesas em ocasiões especiais, como chás da tarde, encontros ou presentes personalizados.', 'Avançado', '2 e 3 horas', 'R$ 30,00 e R$ 40,00', 'Pode ser feito em outras cores de base (como branco, bege ou verde-claro) e com flores em cores variadas (vermelho, lilás, azul ou até multicoloridas), formando coleções sazonais. Também pode virar jogo americano maior, mantendo o mesmo estilo floral.');
INSERT INTO public.products VALUES (54, 'Acessório de Cabelo', '1757987524705-acessorioCabelo10.jpg', 'Tiara Girassol', 'Tiara artesanal feita em crochê, com base bege e aplicação de quadradinhos com flores de girassol. O contraste das cores quentes do girassol com a neutralidade do fundo cria um acessório delicado e alegre, ideal para dar um toque boho e romântico ao visual. Pode ser usada no dia a dia ou em ocasiões especiais, combinando com looks casuais e estilosos.', 'Intermediário', '2 e 3 horas', 'R$ 35,00 e R$ 50,00', 'Pode ser feita em outras cores de flores (como margaridas, rosas ou lavandas) ou com fio mesclado para dar um efeito diferenciado. Outra opção é adaptar o modelo para faixa de bebê ou pulseira de florzinhas.');
INSERT INTO public.products VALUES (55, 'Chaveiro', '1757987644445-chaveiro10.jpg', 'Chaveiro Flor', 'Chaveiro artesanal feito em crochê com formato de flor de cinco pétalas. Disponível em diversas cores, é um acessório delicado, versátil e alegre, que pode ser usado tanto para organizar chaves quanto como enfeite de bolsas, mochilas ou estojos. O detalhe central em cor contrastante valoriza ainda mais o design, deixando a peça divertida e charmosa.', 'Básico', '2o minutos e 30 minutos por unidade', 'R$ 8,00 e R$ 15,00', 'Pode ser feito em temas especiais, como flores vermelhas para o Dia dos Namorados, flores amarelas para a primavera ou até flores com fio brilhante para lembrancinhas de festas e casamentos. Também pode virar pingente de carro ou acessório para zíper de mochila.');
INSERT INTO public.products VALUES (56, 'Roupa', '1757987920243-roupa9.jpg', 'Top Cropped Floral', 'Top cropped feito à mão em crochê, no tom bege suave, com aplicação de pequenas flores lilás bordadas por toda a peça. O modelo possui alças largas e laterais abertas, trazendo frescor e estilo para os dias quentes. Delicado e romântico, é ideal para looks casuais com shorts, saias ou jeans, além de ser uma peça coringa para festivais, encontros ao ar livre e passeios de verão.', 'Avançado', '12 e 15 horas', 'R$ 120,00 e R$ 180,00', 'Pode ser personalizado em outras cores (flores em tons de rosa, azul, amarelo) ou até mesmo em versão monocromática. Outra ideia é criar conjuntinhos com saia ou short em crochê combinando, aumentando o valor agregado do trabalho.');
INSERT INTO public.products VALUES (57, 'Roupa', '1757987996148-roupa10.jpg', 'Top Cropped Vinho com Laços', 'Top artesanal em crochê, confeccionado no tom vinho profundo, com delicados detalhes em bege nas bordas e acabamento em bico rendado. As alças largas recebem laços de fita de cetim, trazendo um charme romântico e sofisticado. O recorte em “V” na barra alonga a silhueta, tornando a peça elegante e versátil. Perfeito para ocasiões especiais, jantares ou para compor looks estilosos e modernos.', 'Avançado', '10 e 14 horas', 'R$ 130,00 e R$ 190,00', 'Pode ser feito em outras combinações de cores, como preto com detalhes dourados, branco com rosa claro ou azul marinho com bege. Também é possível variar as alças, trocando os laços de cetim por tiras ajustáveis em crochê, para dar um ar mais casual.');
INSERT INTO public.products VALUES (58, 'Porta Livro', '1757988102152-portaLivro8.jpg', 'Porta-Livros Envelope', 'Porta-livros artesanal em formato envelope, feito em crochê com ponto rendado que une charme e praticidade. Ideal para proteger livros, cadernos, planners ou até mesmo usar como clutch em produções casuais. Disponível em cores suaves e modernas, como verde musgo e rosa bebê, cada peça é finalizada com detalhes delicados, como botões ou cordões ajustáveis.', 'Intermediário', '4 e 6 horas', 'R$ 70,00 e R$ 110,00', 'Você pode variar os tamanhos para adaptar a diferentes livros (bolsos, médios e grandes) e até personalizar com bordados ou aplicações em crochê, como flores e corações.');
INSERT INTO public.products VALUES (59, 'Porta Livro', '1757988209226-portaLivro9.jpg', 'Porta-Livros/Tablet em Crochê', 'Peça artesanal em crochê, feita no ponto granny square, com mistura de verdes que remetem à natureza. Funcional e charmoso, esse porta-livros também serve como capa para Kindle, tablet ou cadernos. O fechamento com botão garante segurança e praticidade, protegendo seus itens no dia a dia ou em viagens.', 'Básico e intermediário', '3 e 5 horas', 'R$ 65,00 e R$ 95,00', 'Você pode oferecer em diferentes combinações de cores ou até personalizar com botões temáticos (madeira, florais ou divertidos).');
INSERT INTO public.products VALUES (60, 'Bolsa', '1757988327271-bolsa8.jpg', 'Bolsa em Crochê Estilo Tote', 'Bolsa leve, moderna e sustentável, feita em crochê com fio de malha.
Seu formato estilo tote com pontos abertos dá um ar despojado e perfeito para o dia a dia. Ideal para levar em passeios, praia, compras ou até como bolsa complementar no look.', 'Básico', '4 e 6 horas', 'R$ 80,00 e R$ 120,00', 'Você pode oferecer em diferentes cores e tamanhos, ou até customizar com forro interno, flores aplicadas ou botões de madeira para deixar ainda mais exclusiva.');
INSERT INTO public.products VALUES (61, 'Porta Livro', '1757988487754-portaLivro10.jpg', 'Porta-Livro Corações', 'Capa artesanal feita em crochê, com fundo vermelho e delicados coraçõezinhos brancos distribuídos em toda a peça. Além de proteger livros, tablets ou e-readers de arranhões, é também um acessório estiloso e cheio de personalidade. Ideal para presentear alguém especial ou carregar seus itens preferidos com muito charme.', 'Intermediário', '3 e 4 horas', 'R$ 45,00 e R$ 65,00', 'Pode ser feito em outras combinações de cores (preto com vermelho, azul com branco, rosa com lilás). Também é possível acrescentar forro interno em tecido para maior durabilidade ou fechar com botão para mais segurança.');
INSERT INTO public.products VALUES (62, 'Bolsa', '1757988601812-bolsa9.jpg', 'Bolsa Moranguinho', 'Bolsa artesanal feita em crochê, com base bege e aplicação de pequenos morangos vermelhos em toda a superfície. O destaque fica para o chaveirinho de morango com florzinha, que dá ainda mais charme e delicadeza. É uma peça leve, divertida e cheia de estilo, perfeita para usar no dia a dia ou em passeios ao ar livre.', 'Intermediário e avançado', '6 e 8 horas', 'R$ 120,00 e R$ 160,00', 'Pode ser feita em outras versões frutadas, como bolsa de cerejinha, limão ou laranja. Outra ideia é variar a cor de fundo (preto, rosa, verde claro) para criar edições personalizadas. Também é possível adicionar forro interno em tecido para maior durabilidade e segurança.');
INSERT INTO public.products VALUES (63, 'Marca Página', '1757988948561-marcaPagina7.jpg', 'Marca-Página Corações', 'Marca-páginas artesanal feito em crochê, com uma sequência de corações entrelaçados em tom de rosa, finalizado com franja delicada na ponta. Além de funcional, é um mimo cheio de charme, perfeito para acompanhar leituras ou para ser dado como presente especial.', 'Básico e Intermediário', '30 minuto e 1 horas', 'R$ 12,00 e R$ 20,00', 'Pode ser feito em diferentes cores (vermelho, lilás, azul ou multicolorido), criando variações personalizadas. Também pode ser vendido em kits temáticos, como conjunto de 3 ou 5 marca-páginas para presentear leitores apaixonados.');
INSERT INTO public.products VALUES (64, 'Marca Página', '1757989058024-marcaPagina8.jpg', 'Marca-Página Cachorrinho', 'Marca-páginas artesanal em formato de cachorrinho, feito em crochê com fio marrom e detalhes em branco no focinho e coleira. Além de super útil, é um acessório divertido e criativo que deixa a leitura ainda mais charmosa. Ideal para presentear amantes de livros e apaixonados por pets.', 'Intermediário', '1 e 2 horas', 'R$ 25,00 e R$ 35,00', 'Pode ser feito em diferentes cores de fios para personalizar conforme a raça do cachorro (preto, caramelo, branco, mesclado). Outra ideia é criar uma coleção com diferentes animais (gato, coelho, raposa) para atrair ainda mais os apaixonados por leitura e bichinhos.');
INSERT INTO public.products VALUES (65, 'Bolsa', '1757989156373-bolsa10.jpg', 'Bolsa Margaridas e Abelhinhas', 'Bolsa artesanal feita em crochê, na cor verde musgo, com bordados delicados de margaridas brancas e abelhinhas amarelas. O design alegre e cheio de charme transmite frescor e naturalidade, sendo ideal para compor looks leves e despojados. Uma peça única que combina praticidade e estilo, perfeita para passeios, piqueniques e encontros casuais.', 'Intermediário', '6 e 8 horas', 'R$ 120,00 e R$ 160,00', 'Pode ser feita em outras cores de base (bege, azul, lilás) e com diferentes bordados (flores do campo, girassóis, borboletas). Também pode ganhar forro interno em tecido para maior resistência e acabamento refinado.');
INSERT INTO public.products VALUES (66, 'Marca Página', '1757989236360-marcaPagina9.jpg', 'Marca-página Rosa Vermelha', 'Marca-página delicado e artesanal, feito em crochê, com uma linda rosa vermelha e haste verde. O design romântico e elegante transforma a experiência da leitura em um momento ainda mais especial, sendo também uma ótima opção de presente simbólico para amantes de livros e flores.', 'Intermediário', '1 e 2 horas', 'R$ 20,00 e R$ 30,00', 'Pode ser feito em outras cores de rosa (branca, amarela, rosa clara) ou adaptado para outras flores, como girassol, lavanda ou margarida. Também pode ser vendido em kits temáticos de flores.');
INSERT INTO public.products VALUES (67, 'Porta Copo', '1757989836145-portaCopo8.jpg', 'Porta-copo Flor de Lavanda', 'Porta-copos artesanal feito em crochê, com design floral que imita pequenas flores de lavanda em tons de lilás e roxo, com detalhes em verde. Além de proteger a mesa, é uma peça charmosa e delicada, perfeita para quem ama reunir beleza e funcionalidade no dia a dia. Ideal para decorar a mesa em chás da tarde, cafés especiais ou como presente criativo e elegante.', 'Intermediário', '1 e 2 horas', 'R$ 15,00 e R$ 25,00', 'Pode ser feito em outras paletas de cores (como girassol, margarida ou rosas), ou adaptado para sousplat, criando um conjunto completo de mesa. Também fica lindo como base para vasinhos decorativos.');
INSERT INTO public.products VALUES (68, 'Porta Copo', '1757989932543-portaCopo9.jpg', 'Porta-copo Abacate', 'Porta-copos artesanal em crochê, inspirado no formato divertido e colorido do abacate. Produzido em camadas de verde, amarelo e marrom, imitando a fruta de forma criativa e charmosa. Além de proteger a mesa de manchas e arranhões, traz um toque descontraído e moderno para sua decoração. Ideal para presentear, usar em cafés da manhã, brunch ou encontros entre amigos.', 'Básico e intermediário', '40 minutos e 1 horas', 'R$ 12,00 e R$ 18,00', 'Pode ser feito em conjunto com outros modelos de frutas (melancia, laranja, limão) formando um kit temático tropical');
INSERT INTO public.products VALUES (69, 'Porta Copo', '1757990024648-portaCopo10.jpg', 'Porta-copo Limão Siciliano', 'Porta-copos artesanal feito em crochê, inspirado no frescor e na leveza do limão siciliano. Em tom amarelo vibrante, com detalhes em verde (folhinha) e uma delicada flor branca, cada peça traz charme e alegria para sua mesa. Ideal para servir sucos, cafés e drinks, protegendo os móveis com estilo e um toque tropical.', 'Intermediário', '50 minutos e 1 horas', 'R$ 15,00 e R$ 20,00', 'Pode ser vendido em kits temáticos de frutas, junto com porta-copos de abacate, laranja, melancia etc. Uma ótima ideia para presentes criativos ou decoração de verão.');
INSERT INTO public.products VALUES (70, 'Marca Página', '1757990097410-marcaPagina10.jpg', 'Marca-página Cogumelo', 'Marca-páginas artesanal feito em crochê no formato de cogumelo amanita, com caule branco, chapéu vermelho com pintinhas brancas e caule verde alongado que termina em folhas delicadas. Um acessório encantador e criativo, perfeito para quem ama natureza, leitura e peças únicas feitas à mão. Ideal para presentear leitores ou deixar sua leitura ainda mais especial.', 'Intermediário', '1 e 2 horas', 'R$ 18,00 e R$ 28,00', 'Pode ser combinado em kits de marca-páginas temáticos da natureza, junto com modelos de flor, folhas ou borboleta. Também pode ser vendido em caixinhas decoradas, como opção de presente criativo para amantes de livros.');


--
-- TOC entry 4851 (class 0 OID 0)
-- Dependencies: 217
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 70, true);


--
-- TOC entry 4697 (class 2606 OID 42099)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


-- Completed on 2025-09-15 23:36:33

--
-- PostgreSQL database dump complete
--

