--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-09-14 18:47:49

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 42092)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id integer NOT NULL,
    category character varying(100) NOT NULL,
    image text NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    difficulty_level character varying(50) NOT NULL,
    "time" text NOT NULL,
    price text NOT NULL,
    suggestion text
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 42091)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.products_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.products_id_seq OWNER TO postgres;

--
-- TOC entry 4850 (class 0 OID 0)
-- Dependencies: 217
-- Name: products_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.products_id_seq OWNED BY public.products.id;


--
-- TOC entry 4695 (class 2604 OID 42095)
-- Name: products id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products ALTER COLUMN id SET DEFAULT nextval('public.products_id_seq'::regclass);


--
-- TOC entry 4844 (class 0 OID 42092)
-- Dependencies: 218
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.products VALUES (1, 'Chaveiro', '1757779509909-chaveiro1.jpeg', 'Girassol, Margarida e Rosa', 'Chaveiro artesanal feito em crochê em formato de flor. Pode ser produzido em diferentes cores, como girassol (amarelo e marrom), margarida (branco e amarelo) e flor decorativa (rosa e branco). A peça é delicada, versátil e pode ser usada tanto como acessório para chaves quanto para bolsas e mochilas, trazendo um toque criativo e personalizado.', 'Fácil a intermediário', '1h a 1h30 por unidade', 'R$ 18,00 e R$ 30,00', 'Uma ótima ideia para valorizar ainda mais a peça é oferecer personalizações, como acrescentar nomes com miçangas ou iniciais em letras, tornando o chaveiro exclusivo para cada cliente. Também pode-se variar nas linhas, utilizando fios com brilho metálico para criar detalhes diferenciados e atrativos. Outra possibilidade é vender kits de flores em diferentes cores, o que aumenta o ticket médio e agrada quem gosta de ter várias opções para combinar. Além disso, investir em uma embalagem simples, como saquinhos de organza ou caixinhas de papel craft, traz um charme especial e faz com que a peça seja vista não apenas como um chaveiro, mas como um presente artesanal cheio de carinho.');
INSERT INTO public.products VALUES (2, 'Chaveiro', '1757879245774-chaveiro2.jpg', 'Água-viva', 'Chaveiro artesanal em crochê em formato de água-viva, com base arredondada e tentáculos feitos em cordões torcidos, criando um efeito realista e delicado. As cores suaves em degradê, como azul com branco ou rosa com branco, dão um ar alegre e lúdico, tornando a peça perfeita para decorar chaves, bolsas ou mochilas, além de ser uma opção encantadora de presente artesanal.', 'Intermediário', '1h30 e 2h por unidade', 'R$ 25,00 a R$ 40,00', 'Essa peça pode ficar ainda mais especial se for vendida em combinações temáticas, como kit de animais marinhos (água-viva, estrela-do-mar, peixinho). Outra ideia é usar fios com efeito degradê ou mesclados, que destacam os tentáculos e dão movimento à peça. Também é possível acrescentar olhos de miçanga ou bordados para dar expressão e deixá-la mais divertida. Embalar em saquinhos transparentes com etiqueta artesanal reforça o valor de produto feito à mão e a torna ideal para lembrancinhas criativas.');
INSERT INTO public.products VALUES (3, 'Roupa', '1757879420421-roupa1.jpg', 'Blusa Cropped Peplum', 'Blusa cropped artesanal feita em crochê, no estilo peplum, com parte superior ajustada em pontos canelados e parte inferior soltinha com babados delicados. As alças finas com amarração nos ombros deixam a peça ainda mais charmosa e versátil. O modelo, em vermelho vibrante, é moderno e elegante, perfeito para compor looks casuais ou românticos.', 'Intermediário a avançado', '10 a 15 horas', 'R$ 120,00 e R$ 200,00', 'Essa blusa pode ser ainda mais valorizada se for oferecida em diferentes cores, especialmente tons neutros como bege, branco e preto, além de versões em degradê para um visual moderno. Também pode ser feita sob medida, garantindo caimento perfeito para cada cliente. Outra ideia é incluir detalhes extras, como botões decorativos ou aplicações delicadas, para agregar valor. Além disso, investir em ensaios fotográficos que mostrem combinações de looks ajudará a destacar a peça como uma opção estilosa e versátil para o guarda-roupa.');
INSERT INTO public.products VALUES (4, 'Porta Livro', '1757879572357-portaLivro1.jpg', 'Capa Porta-livro com Bolso', 'Capa artesanal em crochê feita sob medida para proteger livros ou cadernos, confeccionada em fio cru com detalhe de coração vermelho em square aplicado na parte da frente. Possui bolso funcional que pode ser usado para guardar canetas, marcadores de página e pequenos acessórios. O acabamento lateral em pontos cruzados vermelhos dá um charme extra e reforça o estilo handmade. É uma peça prática, delicada e perfeita para quem ama leitura e organização.', 'Intermediário', '6 a 8 horas', 'R$ 80,00 e R$ 120,00', 'Essa peça pode ser personalizada em diversas cores, com diferentes motivos no square central (flores, estrelas, iniciais ou símbolos), tornando-a exclusiva para cada cliente. Outra ideia é oferecer tamanhos diferentes para livros de bolso, médios e grandes, ou até mesmo para tablets e agendas, ampliando as possibilidades de uso. Embalagens simples, como saquinhos de tecido ou papel craft com laço de barbante, dão um toque especial e fazem com que a peça seja ideal também para presente.');
INSERT INTO public.products VALUES (5, 'Porta Livro', '1757879691850-portaLivro2.jpg', 'Capa Porta-livro em Xadrez', 'Capa artesanal em crochê feita com padrão xadrez em duas cores, resultando em um visual moderno e delicado. O fechamento é feito com um botão branco que garante praticidade e segurança para proteger o livro. Além de funcional, é uma peça decorativa que combina charme retrô com estilo contemporâneo, disponível em combinações como rosa e branco ou verde e branco. Ideal para quem gosta de levar livros na bolsa sem amassar ou sujar, ou simplesmente para deixar a estante mais bonita e personalizada.', 'Intermediário', '6 a 9 horas', 'R$ 90,00 e R$ 130,00', 'Esse modelo pode ser oferecido em várias combinações de cores, desde tons pastéis para um visual mais delicado até cores fortes para um estilo mais ousado. Também é possível personalizar com iniciais bordadas ou etiquetas de couro sintético com nome, tornando a peça única. Outra ideia é criar kits com marcadores de crochê combinando, agregando valor ao conjunto e tornando-o um presente completo para amantes da leitura.');
INSERT INTO public.products VALUES (6, 'Roupa', '1757879835560-roupa2.jpg', 'Cropped Marrom Café', 'Top cropped artesanal em crochê, confeccionado na cor marrom café, transmitindo elegância e versatilidade. O modelo possui bojo triangular, decote profundo em V e amarração no pescoço e nas costas, garantindo ajuste perfeito ao corpo. É uma peça leve, confortável e atemporal, ideal para compor looks de verão, praia ou até combinações casuais com jeans, saias e pantalonas.', 'Intermediário', '8 a 12 horas', 'R$ 85,00 e R$ 120,00', 'Esse modelo pode ser produzido em diferentes cores (tons neutros para looks clássicos e cores vibrantes para um visual mais ousado). Também é possível personalizar adicionando detalhes como franjas, bordados ou acabamentos em fio com brilho para ocasiões especiais. Outra ideia é criar conjuntos com saias ou shorts em crochê combinando, tornando o produto ainda mais atrativo como “look completo”.');
INSERT INTO public.products VALUES (7, 'Acessório de Cabelo', '1757880206234-acessorioCabelo1.jpg', 'Faixa de Cabelo Trama Aberta', 'Faixa de cabelo artesanal feita em crochê, no estilo trama aberta, proporcionando leveza e um visual descontraído. Confeccionada em fio cru, combina facilmente com diversos looks, do casual ao mais sofisticado. É um acessório versátil, que pode ser usado tanto para compor produções de verão, quanto para dar um toque estiloso em ocasiões especiais. Além de prática, mantém os fios no lugar com elegância e originalidade.', 'Básico a intermediário', '2 a 4 horas', 'R$ 35,00 e R$ 55,00', 'Essa faixa pode ser feita em diversas cores para combinar com diferentes estilos e estações. Fios com brilho ou tons vibrantes podem trazer um ar mais moderno, enquanto os neutros permanecem clássicos e versáteis. Outra possibilidade é criar kits com duas ou três faixas em cores diferentes, aumentando o valor percebido e atraindo quem gosta de variar os acessórios.');
INSERT INTO public.products VALUES (8, 'Bolsa', '1757880335503-bolsa1.jpg', 'Bolsa Fundo do Mar', 'Bolsa artesanal em crochê, confeccionada em fio branco com aplicações inspiradas no mar: estrela-do-mar azul, concha bege e uma charmosa água-viva azul com tentáculos em fio solto. Com alça em crochê no mesmo tom, a peça é leve, prática e perfeita para compor looks de verão ou acompanhar passeios descontraídos. O design criativo transmite frescor e um toque divertido, tornando-a ideal tanto para uso casual quanto para quem ama acessórios exclusivos e temáticos.', 'Intermediário a avançado', '12 a 16 horas', 'R$ 130,00 e R$ 180,00', 'Essa bolsa pode ser feita em versões temáticas diferentes, como “florais”, “borboletas” ou “frutas tropicais”, ampliando a coleção. Outra ideia é criar uma linha completa “Fundo do Mar”, incluindo tiaras, chaveiros e até cropped combinando, para quem gosta de conjuntos. Adicionar forro interno em tecido também aumenta a durabilidade e o valor percebido.');
INSERT INTO public.products VALUES (9, 'Chaveiro', '1757880505638-chaveiro3.jpg', 'Chaveiro Amigurumi Totoro', 'Mini chaveiro feito em crochê no estilo amigurumi, inspirado no personagem Totoro, do estúdio Ghibli. Confeccionado em fio cinza com barriguinha branca e olhinhos aplicados, transmite delicadeza e muito charme. Compacto e leve, é perfeito para decorar chaves, bolsas e mochilas, trazendo um toque divertido e único ao dia a dia.', 'Intermediário', '2 a 3 horas cada unidade', 'R$ 25,00 e R$ 40,00 por unidade', 'Esses chaveiros já são naturalmente encantadores, mas você pode valorizar ainda mais criando uma coleção com outros personagens fofos no mesmo estilo, como gatinhos, pandas ou coelhinhos, ampliando as opções para quem gosta de variar. Outra ideia é oferecer kits temáticos, juntando dois ou três chaveiros em uma mesma compra, o que pode atrair clientes que desejam presentear ou colecionar. Além disso, a personalização é um grande diferencial: bordar iniciais no verso ou brincar com diferentes combinações de cores transforma cada peça em algo único, agregando valor e tornando o chaveiro ainda mais especial para quem compra.');
INSERT INTO public.products VALUES (10, 'Roupa', '1757880830165-roupa3.jpg', 'Top cropped em formato de flor', 'Este é um top cropped de crochê feito à mão, com um design central em forma de flor. O miolo da flor é de uma cor (amarelo), as pétalas são de duas cores diferentes (rosa e branco), e há um contorno de crochê branco nas extremidades de cada pétala, o que dá um acabamento delicado e ondulado. A peça é sem alças, com uma única alça de crochê que se amarra no pescoço. Sua parte inferior é mais curta, mostrando o abdômen. A peça é fresca e ideal para dias quentes.

', 'Intermediário', '10 a 15 horas', 'R$ 100,00 a R$ 250,00', 'Essa peça é perfeita para um look de verão ou para festivais de música. Combine-a com uma saia longa de tecido leve ou com shorts jeans de cintura alta para um visual descontraído e elegante. Uma rasteirinha ou um tênis branco simples completam o visual, e você pode adicionar alguns acessórios como colares delicados ou pulseiras finas. Para um dia mais fresco, use a peça por baixo de uma jaqueta jeans ou um cardigan leve.');
INSERT INTO public.products VALUES (11, 'Bolsa', '1757881291690-bolsa2.jpg', 'Bolsa Coração', 'Bolsa artesanal em crochê no formato de coração, feita com fio rosa claro e alça larga também em crochê. O fechamento é simples, utilizando fitas de cetim nas laterais, o que traz um charme delicado e romântico à peça. Compacta e leve, é perfeita para carregar pequenos objetos do dia a dia com estilo e personalidade. Combina tanto com looks casuais quanto com produções mais femininas e delicadas, além de ser uma ótima opção de presente artesanal.
', 'Intermediário', '5 e 8 horas', 'R$ 90,00 e R$ 150,00', 'Essa bolsa pode ser explorada em diferentes cores, como vermelho para um estilo mais apaixonado, branco para um toque mais delicado ou até multicolorida para um visual divertido. Adicionar forro de tecido interno aumenta a durabilidade e a praticidade da peça, permitindo carregar objetos com mais segurança. Pequenos detalhes extras, como flores de crochê aplicadas, pérolas ou botões personalizados, podem agregar ainda mais valor. Também é possível criar versões infantis em tamanhos menores ou versões maiores como bolsas de ombro, ampliando as opções para diferentes públicos.');
INSERT INTO public.products VALUES (12, 'Marca Página', '1757881496995-marcaPagina1.jpg', 'Marca-página Margarida e Girassol', 'Marca-página artesanal feito em crochê, composto por pequenas flores unidas em sequência, resultando em um acessório delicado e funcional. Cada extremidade é finalizada com um tassel que garante charme extra e ajuda a manter o marcador firme entre as páginas. As cores podem variar entre tons vibrantes, como amarelo e laranja, ou tons neutros e suaves, como branco e bege, permitindo combinações que vão do alegre ao romântico. É um item prático para leitores que desejam marcar suas páginas com estilo, além de ser uma opção encantadora de presente artesanal.', 'Básico e intermediário', '1h30 a 3h por unidade', 'R$ 25,00 e R$ 45,00', 'Esse modelo pode ser oferecido em diversas paletas de cores, como tons pastéis para um estilo delicado, cores fortes para um visual vibrante ou até combinações sazonais, como vermelho e verde no Natal ou laranja e preto para o Halloween. Também é possível criar kits com dois ou três marca-páginas diferentes, tornando-os presentes criativos e acessíveis para amantes da leitura. Outra ideia é personalizar com pequenas miçangas ou pérolas no centro das flores, dando um toque sofisticado e exclusivo.');
INSERT INTO public.products VALUES (13, 'Porta Copos', '1757881824414-portaCopo1.jpg', 'Porta-copos Flor Sorridente', 'Porta-copos artesanal feito em crochê no formato de flor, com centro amarelo e pétalas brancas. O detalhe do rostinho sorridente bordado no centro deixa a peça divertida, alegre e cheia de personalidade, ideal para trazer charme à mesa e proteger superfícies de respingos e calor das bebidas. Além de funcional, é um item decorativo que combina com ambientes descontraídos e acolhedores, perfeito para cafés da manhã, encontros entre amigos ou para dar de presente em kits criativos.', 'Básico e intermediário', '1h a 2h por unidade', 'R$ 15,00 e R$ 25,00', 'Essa peça pode ser oferecida em diferentes combinações de cores, como flores coloridas (rosa, azul, lilás, laranja) ou até em versão minimalista (branco e preto) para se adaptar a vários estilos de decoração. Também é possível montar kits temáticos com embalagens personalizadas, que funcionam muito bem como lembrancinhas de aniversário, chá de cozinha, Dia das Mães ou presentes criativos para amigos. Outra ideia é variar os bordados, criando carinhas diferentes (piscando, com óculos, corações nos olhos) para deixar os conjuntos ainda mais divertidos e exclusivos.');
INSERT INTO public.products VALUES (14, 'Chaveiro', '1757882661001-chaveiro4.jpg', 'Chaveiro Flor', 'Chaveiro artesanal feito em crochê no formato de flor de cinco pétalas, em fio branco com detalhe central em rosa claro. É um acessório delicado, leve e funcional, perfeito para personalizar chaves, bolsas e mochilas com um toque artesanal e romântico. Além de ser útil, também é um mimo criativo que pode ser oferecido como lembrancinha em aniversários, chás de bebê, casamentos ou simplesmente como presente carinhoso para alguém especial.', 'Básico', '30 a 50 minutos por unidade', 'R$ 8,00 e R$ 15,00', 'Esse chaveiro pode ser feito em diversas combinações de cores, como flores coloridas para um estilo alegre ou tons pastéis para um visual delicado. Também é possível personalizar com pérolas ou miçangas no centro, ou ainda adicionar etiquetas de couro sintético com nomes para torná-los exclusivos. Oferecer kits temáticos ou embalagens personalizadas aumenta o valor percebido e torna a peça ainda mais atrativa para presentes e lembrancinhas.');
INSERT INTO public.products VALUES (15, 'Roupa', '1757882836368-roupa4.jpg', 'Top Faixa com Nó Torcido', 'Top artesanal em crochê confeccionado em listras horizontais nas cores azul bebê e branco. O destaque da peça é o nó torcido na parte frontal, que cria um recorte moderno e valoriza o busto, deixando o visual estiloso e descontraído. Feito à mão com pontos simples e fio confortável, é uma peça leve, fresca e perfeita para os dias de verão. Pode ser usado tanto como saída de praia quanto em looks casuais, combinando com shorts, saias ou calças de cintura alta.', 'Intermediário', '6 a 10 horas', 'R$ 120,00 e R$ 180,00', 'Esse modelo pode ser explorado em diferentes combinações de cores, desde tons pastéis delicados até cores vibrantes e contrastantes. Também é possível adaptar a peça com alças removíveis ou amarrações nas costas, oferecendo mais sustentação e variedade de estilos. Para valorizar ainda mais o trabalho, vale oferecer versões personalizadas sob medida, tornando o top exclusivo para cada cliente.');
INSERT INTO public.products VALUES (16, 'Roupa', '1757883001690-roupa5.jpg', 'Top Moranguinho', 'Top artesanal em crochê inspirado no estilo retrô e romântico, confeccionado em branco com detalhes em vermelho e verde. A peça apresenta alças largas, acabamento delicado em ponto fantasia e aplicação de moranguinhos em crochê, que trazem um charme divertido e exclusivo. O fechamento frontal é feito com amarração em cordão verde, proporcionando ajuste perfeito ao corpo e um toque de originalidade. É uma peça leve, estilosa e ideal para looks de verão, podendo ser combinada com shorts, saias ou jeans para um visual despojado e cheio de personalidade.', 'Intermediário a avançado', '8 a 12 horas', 'R$ 140,00 e R$ 200,00', 'Esse top pode ser adaptado em outras frutas, como cerejinhas, laranjas ou limões, criando uma coleção temática divertida e colecionável. Outra ideia é oferecer personalização de cores, como tons pastéis para um visual delicado ou combinações vibrantes para um estilo ousado. Também é possível produzir versões mais compridas como cropped estilo regata ou até vestidos curtos seguindo o mesmo conceito, ampliando as opções para diferentes clientes.');
INSERT INTO public.products VALUES (17, 'Acessório de Cabelo', '1757883134012-acessorioCabelo2.jpg', 'Tiara Faixa', 'Tiara artesanal em crochê feita com ponto rendado delicado, em fio cru. É uma peça versátil e confortável, que pode ser usada tanto para dar um toque romântico ao look quanto para manter os cabelos no lugar de forma charmosa. Seu design leve e trabalhado à mão valoriza penteados soltos ou presos, combinando com diferentes estilos — do casual ao boho. É perfeita para complementar produções de verão, passeios ao ar livre ou até mesmo ocasiões especiais em que se busca um acessório único e artesanal.', 'Intermediário', '2 a 4 horas', 'R$ 25,00 e R$ 45,00', 'Essa tiara pode ser feita em várias cores para combinar com diferentes estilos e estações. Tons neutros como bege, branco e cinza dão um ar minimalista, enquanto cores vivas como vermelho, azul ou amarelo deixam a peça mais divertida. Também é possível acrescentar detalhes como pérolas costuradas, flores pequenas em crochê ou até fios com brilho para versões mais sofisticadas. Uma boa estratégia de venda é oferecer kits com 2 ou 3 unidades em cores variadas, ideais para quem gosta de mudar o visual sem abrir mão do artesanato.');
INSERT INTO public.products VALUES (18, 'Bolsa', '1757883410920-bolsa3.jpg', 'Bolsa Quadradinhos com Corações', 'Bolsa artesanal feita em crochê com a técnica de granny squares, composta por quadrados vermelhos e brancos decorados com corações em relevo. É uma peça romântica, moderna e super charmosa, ideal para quem ama acessórios únicos e feitos à mão. Além de estilosa, é resistente e prática para o dia a dia, comportando desde itens pessoais até pequenos objetos de uso cotidiano.', 'Intermediário', '8 a 12 horas', 'R$ 120,00 e R$ 180,00', 'É possível explorar diferentes paletas de cores para adaptar a bolsa a diferentes estilos, como combinações suaves em tons pastéis ou contrastes mais modernos em cores vibrantes. Outra ideia é adicionar forro em tecido, o que garante maior resistência e funcionalidade, além de permitir guardar objetos menores com segurança. Oferecer versões personalizadas sob encomenda pode valorizar ainda mais o trabalho, tornando cada bolsa exclusiva e especial para a cliente.');
INSERT INTO public.products VALUES (19, 'Bolsa', '1757883708587-bolsa4.jpg', 'Bolsa Summer', 'Bolsa artesanal em crochê confeccionada com fio de malha branco, que garante estrutura firme e visual moderno. O modelo apresenta um formato retangular compacto, ideal para levar o essencial com estilo. A alça larga, também em crochê, é fixada com argolas metálicas que trazem resistência e um toque sofisticado. O detalhe especial fica por conta do enfeite em acrílico transparente em forma de flor, que adiciona delicadeza e charme ao design minimalista. É uma peça versátil, perfeita para passeios na praia, encontros casuais ou até para compor looks urbanos descontraídos.', 'Básico e intermediário', '6 a 8 horas', 'R$ 130,00 e R$ 180,00', 'Esse modelo pode ganhar versões ainda mais exclusivas com o uso de cores vibrantes ou combinações bicolores. Outra ideia é acrescentar forro interno em tecido, oferecendo mais segurança e durabilidade. O enfeite pode ser personalizado — como flores de crochê, pompons ou aplicações em metal — para atender diferentes estilos e preferências de clientes.');
INSERT INTO public.products VALUES (20, 'Marca Página', '1757883903953-marcaPagina2.jpeg', 'Marca-página Xícara de Café', 'Marca-página artesanal em crochê no formato de uma delicada xícara de café branca com interior marrom, que representa o café servido. O fio longo e fino se estende até um pingente em forma de tassel marrom, criando um detalhe charmoso e funcional. A peça é leve, criativa e ideal para acompanhar momentos de leitura, trazendo aconchego e um toque artesanal único ao livro. Além de útil, é um presente encantador para amantes de café e leitura.', 'Básico e intermediário', '2 a 3 horas', 'R$ 25,00 e R$ 40,00', 'Esse modelo pode ser personalizado em diferentes cores para representar outras bebidas, como chá ou chocolate quente, além de variar o tom do tassel para criar combinações divertidas. Outra ideia é montar kits com diferentes versões do marca-página, tornando-o um produto perfeito para presentes criativos e lembrancinhas temáticas.');
INSERT INTO public.products VALUES (21, 'Marca Página', '1757884869591-marcaPagina3.jpg', 'Marca-página Laço', 'Marca-página delicado em crochê, composto por um laço rosa na parte superior e uma pequena flor na extremidade do fio branco, finalizada com detalhe em pérola no centro. O design transmite romantismo e sutileza, tornando a leitura ainda mais encantadora. É uma peça artesanal charmosa, perfeita para marcar páginas de forma criativa e dar um toque especial aos livros.', 'Intermediário', '3 a 4 horas', 'R$ 30,00 e R$ 50,00', 'Esse modelo pode ser adaptado em diferentes cores e combinações, como laços em tons pastéis ou vibrantes, além de variações de flores com ou sem pérolas. Também é possível criar coleções temáticas, oferecendo kits com diferentes modelos de marca-página, tornando o produto ainda mais atrativo para presentes delicados e personalizados.');
INSERT INTO public.products VALUES (22, 'Chaveiro', '1757885037829-chaveiro5.jpg', 'Chaveiro Laço', 'Chaveiro artesanal em formato de laço, confeccionado em crochê com pontos firmes e bem estruturados. O design transmite delicadeza e charme, ideal para quem gosta de acessórios românticos e elegantes. Cada peça recebe detalhes especiais com miçangas e pedrarias, que acrescentam sofisticação e tornam o chaveiro ainda mais único. Disponível em cores como rosa e branco, é um acessório versátil que pode ser usado para enfeitar chaves, bolsas ou mochilas, agregando um toque de personalidade ao dia a dia.', 'Básico e intermediário', '2 a 3 horas', 'R$ 18,00 e R$ 35,00', 'Esse modelo pode ser confeccionado em diferentes cores e tamanhos, possibilitando desde versões delicadas e minimalistas até laços maiores e mais chamativos. Também é possível criar coleções temáticas, como chaveiros em tons pastéis, vibrantes ou metalizados, oferecendo opções personalizadas que agradam a diferentes perfis de clientes.');
INSERT INTO public.products VALUES (23, 'Roupa', '1757885157996-roupa6.jpg', 'Top Cropped Toamara-que-Caia', 'Um top cropped tomara-que-caia confeccionado em crochê, que combina charme e frescor para dias ensolarados. A parte superior traz listras delicadas em rosa e branco, com detalhe central franzido que valoriza o busto de forma elegante. Já a parte inferior possui acabamento em babado evasê, criando movimento e um caimento leve, que acrescenta feminilidade e estilo ao visual. Confortável e moderno, é perfeito para compor looks casuais com shorts, saias ou calças jeans, sendo também uma ótima opção para ocasiões na praia, passeios ou encontros informais.', 'Intermediário', '6 a 10 horas', 'R$ 85,00 e R$ 150,00', 'Esse modelo pode ser adaptado em diferentes combinações de cores, desde tons vibrantes até os mais neutros. Também pode ganhar variações com alcinhas finas para quem busca mais segurança ou detalhes extras, como aplicação de pérolas ou bordados, tornando-o ainda mais exclusivo.');
INSERT INTO public.products VALUES (24, 'Porta Livro', '1757885338724-portaLivro3.jpg', 'Porta-Livro Rosa Tulipas', 'Porta-livro artesanal em crochê feito à mão na cor rosa bebê, com delicados bordados florais que remetem a pequenos botões de rosas em tom pink com folhas verdes. A peça conta com fechamento em aba com botão, garantindo praticidade e proteção ao livro. Além de funcional, traz um charme romântico e atemporal, ideal para quem deseja transportar ou guardar seus livros de forma elegante e personalizada. Seu design acolhedor transforma a leitura em um momento ainda mais especial, unindo utilidade e beleza em cada detalhe.', 'Intermediário', '8 a 12 horas', 'R$ 90,00 e R$ 150,00', 'Esse modelo pode ser facilmente adaptado em outras cores, como lilás, azul claro ou bege, mantendo os bordados florais em contraste. Também é possível personalizar com iniciais ou pequenos apliques, tornando o porta-livro uma peça exclusiva e perfeita para presentes.');
INSERT INTO public.products VALUES (25, 'Porta Livro', '1757885472244-portaLivro4.jpg', 'Porta-Livro Morango', 'Porta-livro artesanal em crochê inspirado na doçura e no charme do morango. A peça é confeccionada em vermelho vivo, com pequenos pontos brancos que remetem às sementes da fruta. O acabamento em verde, junto ao botão de fechamento, representa as folhinhas do morango, trazendo delicadeza e um visual divertido. Além de proteger o livro contra riscos e desgastes, o acessório transforma a leitura em um momento ainda mais especial, unindo funcionalidade e estilo.', 'Intermediário', '6 a 9 horas', 'R$ 70,00 e R$ 120,00', 'Esse modelo pode ganhar versões em diferentes frutas, como melancia, abacaxi ou laranja, formando uma coleção criativa e alegre. Também é possível personalizar com bordados de flores ou iniciais, tornando a peça exclusiva para cada cliente.');
INSERT INTO public.products VALUES (26, 'Acessório de Cabelo', '1757885658868-acessorioCabelo3.jpg', 'Tiara Corações', 'Tiara artesanal em crochê confeccionada com base em azul marinho e detalhes em branco, formando delicados corações ao longo de toda a peça. O contraste das cores dá um charme especial, enquanto o design leve e macio garante conforto ao usar. Ideal para compor penteados românticos ou dar um toque divertido ao visual do dia a dia, sendo uma opção fofa e versátil para todas as idades.', 'Intermediário', '3 a 5 horas', 'R$ 35,00 e R$ 55,00', 'Esse modelo pode ser feito em diversas combinações de cores, como vermelho e branco para um estilo apaixonado ou tons pastel para um visual delicado. Outra ideia é adaptar o acessório em versão infantil, criando conjuntos mãe e filha.');
INSERT INTO public.products VALUES (27, 'Acessório de Cabelo', '1757885838558-acessorioCabelo4.jpg', 'Tiara Floral', 'Tiara delicada confeccionada em crochê, com base em verde que imita ramos e pequenas flores cor-de-rosa aplicadas ao longo de toda a peça. O acessório é leve, romântico e cheio de detalhes, perfeito para criar um visual natural e encantador. Pode ser usado em ocasiões especiais, como casamentos ao ar livre e festas temáticas, ou no dia a dia para dar um toque boho e feminino ao penteado.', 'Intermediário', '4 a 6 horas', 'R$ 45,00 e R$ 70,00', 'Esse modelo pode ser personalizado com flores em diferentes cores, como lilás, azul ou amarelo, criando versões exclusivas para cada cliente. Outra ideia é adaptar o acessório como guirlanda decorativa ou até mesmo faixa para bebês, tornando-o ainda mais versátil.');
INSERT INTO public.products VALUES (28, 'Acessório de Cabelo', '1757885945614-acessorioCabelo5.jpg', 'Lenço com Squares Florais', 'Lenço artesanal feito em crochê com união de quadradinhos (granny squares) em tom cru, cada um decorado com uma delicada flor central azul com miolo rosa. O acabamento em ondas dá um caimento leve e romântico, transformando o acessório em um charme vintage para compor penteados soltos ou presos. Versátil e estiloso, combina perfeitamente com looks boho, românticos ou casuais.', 'Intermediário', '6 a 8 horas', 'R$ 70,00 e R$ 110,00', 'Você pode criar versões em diferentes combinações de cores (flores amarelas, lilases ou vermelhas, por exemplo) ou até usar fio mesclado para um efeito mais moderno. Outra ideia é aumentar a peça e transformá-la em uma bandana maior ou até em um mini-xale multifuncional.');
INSERT INTO public.products VALUES (29, 'Bolsa', '1757886152592-bolsa5.jpg', 'Bolsa com Fio de Malha Pink', 'Bolsa artesanal confeccionada em crochê com fio de malha na cor pink vibrante. O modelo possui alças curtas integradas à própria estrutura, garantindo resistência e conforto ao carregar. De tamanho médio, é prática e moderna, perfeita para o dia a dia ou para dar um toque fashion em produções casuais. Sua textura encorpada valoriza o trabalho manual e a deixa ainda mais única.', 'Básico e intermediário', '4 a 6 horas', 'R$ 90,00 e R$ 150,00', 'Esse modelo pode ganhar versões em outras cores tendência, como verde oliva, bege, preto ou até combinações bicolores. Também é possível adicionar um forro de tecido com bolsinho interno para maior praticidade e sofisticação.');
INSERT INTO public.products VALUES (30, 'Bolsa', '1757886273782-bolsa6.jpg', 'Bolsa Granny Square Colorida', 'Bolsa artesanal feita em crochê no clássico estilo granny square, unindo cores vibrantes como laranja, rosa, vermelho e lilás, em contraste com o branco cru. O modelo é espaçoso e leve, ideal para usar em passeios, praia ou no dia a dia, trazendo um ar descontraído e retrô. As alças médias permitem carregar no ombro com conforto, enquanto o design colorido dá destaque a qualquer look.', 'Intermediário', '6 a 8 horas', 'R$ 120,00 e R$ 200,00', 'Esse modelo fica incrível em combinações personalizadas — tons pastel para um ar delicado, cores sóbrias para algo sofisticado ou neon para um visual moderno e despojado. Um forro de algodão pode deixar a peça ainda mais resistente e prática.');


--
-- TOC entry 4851 (class 0 OID 0)
-- Dependencies: 217
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 30, true);


--
-- TOC entry 4697 (class 2606 OID 42099)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


-- Completed on 2025-09-14 18:47:50

--
-- PostgreSQL database dump complete
--

